In [2]:
import numpy as np


In [5]:
A = np.array([10, 20, 30, 40, 50])
M = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [6]:
print("\n=== Étape 5 : Broadcasting ===")

addition_scalaire = A + 5
print("A        :", A)
print("A + 5    :", addition_scalaire)
print("Shape A      :", A.shape)
print("Shape A + 5  :", addition_scalaire.shape)


=== Étape 5 : Broadcasting ===
A        : [10 20 30 40 50]
A + 5    : [15 25 35 45 55]
Shape A      : (5,)
Shape A + 5  : (5,)


In [7]:
M = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
vecteur_ligne = np.array([10, 20, 30])

resultat_ligne = M + vecteur_ligne
print("\nM :\n", M)
print("vecteur_ligne :", vecteur_ligne)
print("M + vecteur_ligne :\n", resultat_ligne)
print("Shape M            :", M.shape)
print("Shape vecteur_ligne:", vecteur_ligne.shape)
print("Shape résultat     :", resultat_ligne.shape)



M :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
vecteur_ligne : [10 20 30]
M + vecteur_ligne :
 [[11 22 33]
 [14 25 36]
 [17 28 39]]
Shape M            : (3, 3)
Shape vecteur_ligne: (3,)
Shape résultat     : (3, 3)


In [8]:
vecteur_colonne = np.array([[10],
                            [20],
                            [30]])

resultat_colonne = M + vecteur_colonne
print("\nvecteur_colonne :\n", vecteur_colonne)
print("Shape vecteur_colonne :", vecteur_colonne.shape)
print("M + vecteur_colonne :\n", resultat_colonne)
print("Shape résultat_colonne :", resultat_colonne.shape)



vecteur_colonne :
 [[10]
 [20]
 [30]]
Shape vecteur_colonne : (3, 1)
M + vecteur_colonne :
 [[11 12 13]
 [24 25 26]
 [37 38 39]]
Shape résultat_colonne : (3, 3)


In [9]:
print("\n=== Étape 6 : Calcul vectoriel et filtrage ===")

C = (A * 2) + np.sin(A) - np.mean(A)
print("A :", A)
print("mean(A) :", np.mean(A))
print("C = (A * 2) + sin(A) - mean(A) :", C)
print("Shape C :", C.shape)



=== Étape 6 : Calcul vectoriel et filtrage ===
A : [10 20 30 40 50]
mean(A) : 30.0
C = (A * 2) + sin(A) - mean(A) : [-10.54402111  10.91294525  29.01196838  50.74511316  69.73762515]
Shape C : (5,)


In [10]:
log_A = np.log(A)
masque_log = log_A > 2
print("\nlog(A)      :", log_A)
print("masque_log  :", masque_log)
print("log(A) > 2  :", log_A[masque_log])


log(A)      : [2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]
masque_log  : [ True  True  True  True  True]
log(A) > 2  : [2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]


In [11]:
print("\nShapes récap :")
print("A.shape                :", A.shape)
print("M.shape                :", M.shape)
print("resultat_ligne.shape   :", resultat_ligne.shape)
print("resultat_colonne.shape :", resultat_colonne.shape)
print("C.shape                :", C.shape)


Shapes récap :
A.shape                : (5,)
M.shape                : (3, 3)
resultat_ligne.shape   : (3, 3)
resultat_colonne.shape : (3, 3)
C.shape                : (5,)
